# Generated by Django 6.1.1 on 2026-09-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('media_lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('excerpt_uz', models.CharField(blank=True, max_length=500)),
                ('excerpt_ru', models.CharField(blank=True, max_length=500)),
                ('excerpt_en', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_lib.image')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='news_post', to='content.page')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
