# Generated by Django 6.1.1 on 2026-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory_newspost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
