# Generated by Django 6.1.1 on 2026-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
