# Generated by Django 6.1.1 on 2026-09-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('list', 'List'), ('staff_card', 'Staff card'), ('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
    ]
