# Generated by Django 6.1.1 on 2026-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
