# Generated by Django 6.1.1 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("content", "0006_page_title_en_page_title_ru_page_title_uz")]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("heading", "Heading"),
                    ("paragraph", "Paragraph"),
                    ("list", "List"),
                    ("staff_card", "Staff card"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("document", "Document"),
                    ("gallery", "Gallery"),
                    ("table", "Table"),
                    ("raw_html", "Legacy HTML"),
                ],
                max_length=20,
            ),
        ),
    ]
