# Generated by Django 6.1.1 on 2026-09-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_faculty'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='faculties.faculty'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='reception_days_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='reception_days_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='reception_days_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='departments.department'),
        ),
    ]
