# Generated by Django 6.1.1 on 2026-09-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_staffmember_full_name_per_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
