# Generated by Django 6.1.1 on 2026-09-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_staffmember_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='activity_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='activity_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='activity_uz',
            field=models.TextField(blank=True),
        ),
    ]
