# Generated by Django 6.1.1 on 2026-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_staffmember_activity_en_staffmember_activity_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='institute_role',
            field=models.CharField(blank=True, choices=[('rektor', 'Rektor'), ('prorektor', 'Prorektor')], max_length=20),
        ),
    ]
