# Generated by Django 6.1.1 on 2026-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='uploads/videos/clips/%Y/%m/')),
                ('youtube_id', models.CharField(blank=True, max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-order', '-id'],
            },
        ),
    ]
