# Generated by Django 6.1.1 on 2026-09-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_lib', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_uz', models.CharField(blank=True, max_length=255)),
                ('caption_ru', models.CharField(blank=True, max_length=255)),
                ('caption_en', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media_lib.image')),
            ],
            options={
                'ordering': ['-order', '-id'],
            },
        ),
    ]
