# Generated by Django 6.1.1 on 2026-10-10 05:07

import apps.media_lib.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_lib', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.media_lib.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx'])]),
        ),
    ]
