# Generated by Django 6.1.1 on 2026-09-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0002_faculty_logo'),
        ('media_lib', '0005_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fish', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('region_id', models.PositiveIntegerField(blank=True, null=True)),
                ('district_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qabul arizasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('region_id', models.PositiveIntegerField(blank=True, null=True)),
                ('district_id', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='faculties.faculty')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_lib.document')),
            ],
            options={
                'verbose_name': 'Virtual qabulxona murojaati',
                'ordering': ['-created_at'],
            },
        ),
    ]
