# Generated by Django 6.1.1 on 2026-09-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='faculty', to='content.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
