# Generated by Django 6.1.1 on 2026-09-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
        ('media_lib', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_lib.image'),
        ),
    ]
